require "vmc/version"

require "vmc/cli"
require "vmc/cli/start"
require "vmc/cli/app"
require "vmc/cli/service"
require "vmc/cli/user"
require "vmc/cli/space"
require "vmc/cli/organization"
require "vmc/cli/route"
require "vmc/cli/domain"
